-- DropForeignKey
ALTER TABLE "_ASINToTag" DROP CONSTRAINT "_ASINToTag_B_fkey";

-- AlterTable
ALTER TABLE "Tag" DROP CONSTRAINT "Tag_pkey",
DROP COLUMN "id",
ADD COLUMN     "id" SERIAL NOT NULL,
ADD CONSTRAINT "Tag_pkey" PRIMARY KEY ("id");

-- AlterTable
ALTER TABLE "_ASINToTag" DROP CONSTRAINT "_ASINToTag_AB_pkey",
DROP COLUMN "B",
ADD COLUMN     "B" INTEGER NOT NULL,
ADD CONSTRAINT "_ASINToTag_AB_pkey" PRIMARY KEY ("A", "B");

-- CreateIndex
CREATE INDEX "_ASINToTag_B_index" ON "_ASINToTag"("B");

-- AddForeignKey
ALTER TABLE "_ASINToTag" ADD CONSTRAINT "_ASINToTag_B_fkey" FOREIGN KEY ("B") REFERENCES "Tag"("id") ON DELETE CASCADE ON UPDATE CASCADE;
