version: '3.8'
services:
  db:
    build:
      context: .
      dockerfile: postgres.Dockerfile
    restart: always
    environment:
      POSTGRES_USER: viasuser
      POSTGRES_PASSWORD: viaspassword
      POSTGRES_DB: viasglobal_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    restart: always
    ports:
      - "3001:3000"
    env_file: .env
    environment:
      DATABASE_URL: "postgresql://viasuser:viaspassword@db:5432/viasglobal_db?schema=public"
    depends_on:
      - db

volumes:
  pgdata:
